name: Create Release

on:
  push:
    tags:
      - 'v*' # Trigger on tags with prefix 'v'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Generate Release Notes
      id: release_notes
      uses: actions/github-script@v8
      with:
        script: |
          const { context, github } = require('@actions/github');
          const core = require('@actions/core');
          const tagName = context.ref.replace('refs/tags/', '');
          // Fetch all tags using pagination
          const tags = await github.paginate(github.rest.repos.listTags, {
            owner: context.repo.owner,
            repo: context.repo.repo,
            per_page: 100,
          });

          const currentTagIndex = tags.findIndex(tag => tag.name === tagName);
          if (currentTagIndex === -1 || currentTagIndex === tags.length - 1) {
            core.setOutput('notes', 'No previous tag found.');
            return;
          }

          const previousTag = tags[currentTagIndex + 1].name;
          const { data: commits } = await github.rest.repos.compareCommits({
            owner: context.repo.owner,
            repo: context.repo.repo,
            base: previousTag,
            head: tagName,
          });

          // Only use the first line of each commit message
          const commitMessages = commits.commits.map(commit => {
            const firstLine = commit.commit.message.split('\n')[0];
            return `- ${firstLine}`;
          }).join('\n');
          core.setOutput('notes', `Changes since ${previousTag}:\n\n${commitMessages}`);

    - name: Create GitHub Release
    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_NOTES: ${{ steps.release_notes.outputs.notes }}
      run: |
        printf '%s\n' "$RELEASE_NOTES" > release-notes.txt
        gh release create "${{ github.ref_name }}" \
          --title "${{ github.ref_name }}" \
          --notes-file release-notes.txt \
          --verify-tag
        --verify-tag