name: Greetings

on: [issues, pull_request_target]

permissions:
  issues: write
  pull-requests: write

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
      with:
        egress-policy: audit

    - uses: actions/first-interaction@1c4688942c71f71d4f5502a26ea67c331730fa4d # v3.1.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        issue_message: 'Thank you for your interest in this project. I will get back to you as soon as I can.'
        pr_message: 'Thank you for your PR.'

