# .github/workflows/tag.yml

name: Tag

on:
  push:
    branches:
      - main

jobs:
  Tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: '0'

    - name: Configure git identity
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Get version from package.json
      id: get_version
      run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

    - name: Create and push tag if it doesn't exist
      id: create_tag
      run: |
        if ! git rev-parse v${{ steps.get_version.outputs.version }} >/dev/null 2>&1; then
          echo "Creating tag v${{ steps.get_version.outputs.version }}"
          git tag -a v${{ steps.get_version.outputs.version }} -m "Version ${{ steps.get_version.outputs.version }}"
          git push origin v${{ steps.get_version.outputs.version }}
          echo "tag_created=true" >> $GITHUB_OUTPUT
          echo "The create-release workflow will be triggered automatically to generate release notes and create the release"
        else
          echo "Tag v${{ steps.get_version.outputs.version }} already exists, skipping tag and release creation"
          echo "tag_created=false" >> $GITHUB_OUTPUT
        fi
